### ISSUE TITLE
Build fails with Python 3.8 on Ubuntu 20.04

### ISSUE THREAD

**Issue by he-hesce** [MeVisLab/pythonqt#32]
Dear PythonQt community,

I have been using PythonQt for years with Python 2.7 and Python 3.6. I am now trying to build our project with Python 3.8 on Ubuntu 20.04. However, I get a compilation error as outlined further below. I am using the as of today latest code on master branch, committish 9ea0fcf of 2 December 2020. Am I missing something or is this an issue in PythonQt trunk or an issue with Ubuntu 20.04?

I would very much appreciate the community's and the developers' insight. I very much would like to use the native Ubuntu 20.04 Python and not compile and maintain my own installation.

Thank you.

Relevant error message from compiler:

```
In file included from /usr/include/python3.8/pystate.h:10,
                 from /usr/include/python3.8/genobject.h:11,
                 from /usr/include/python3.8/Python.h:121,
                 from ../../libsrc/PythonQt/src/PythonQtPythonInclude.h:59,
                 from ../../libsrc/PythonQt/src/PythonQt.h:45,
                 from [censored]
/usr/include/python3.8/pythread.h:128:5: error: #error "Require native threads. See https://bugs.python.org/issue31370"
  128 | #   error "Require native threads. See https://bugs.python.org/issue31370"
      |     ^~~~~
/usr/include/python3.8/pythread.h:137:5: error: ‘NATIVE_TSS_KEY_T’ does not name a type
  137 |     NATIVE_TSS_KEY_T _key;
      |     ^~~~~~~~~~~~~~~~
```

**Comment by he-hesce** [comment]
Commenting out the line with:
`#undef _POSIX_THREADS`
in PythonQtPythonInclude.h does solve the above described issue though it's unclear what other side effects this has and how it affects compatibility with 2.7 and 3.6.

**Comment by he-hesce** [comment]
It does seem to work fine with both Python 2.7 (CentOS 7) and Python 3.6 (CentOS 8) without undeffing _POSIX_THREADS. I then also need to use -D_POSIX_THREADS in QMAKE_CXXFLAGS on Ubuntu 20.04.

In any case, we can leave this ticket here in case someone else has a similar problem. Workaround is described in the previous comment.

Developers may choose to consider not undeffing _POSIX_THREADS.
